# 1.2 Introdução a Redes Neurais: do que se alimentam?

Falando em Deep Learning e redes neurais, as entradas são normalmente **tensores**. Nesta seção iremos discutir o que são tensores e como manipulá-los com Numpy.


## O que são tensores?

Tensores são vetores de diferentes dimensões. Você já conhece tensores, os mais comuns tem nomes próprios:

Um tensor 0-dimensional é um **scalar**; um tensor uni-dimensional é um **vetor** (array); um tensor bi-dimensional é uma **matriz** (array de arrays); Um tensor N-dimensional é um... Tensor!

Um **tensor** é qualquer vetor com N-dimensões (por exemplo, um cubo é um tensor de 3 dimensões). Vale salientar que, tecnicamente, o conceito de tensor engloba todos eles. Porém, na prática, chamamos de tensores os vetores com 3 ou mais dimensões. Veja [**esse vídeo**](https://www.youtube.com/watch?v=f5liqUk0ZTw) para mais detalhes.


Ainda pensando dessa forma, poderíamos imaginar um tensor 4-dimensional como um **array de cubos**; um tensor 5-dimensional seria uma **matriz de cubos**; um tensor 6-dimensional seria um **cubo de cubos**, e assim por diante...

<img align='center' src='https://media3.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif'>

## Visualização matemática

De maneira matemática, você pode pensar em tensores da seguinte forma:
![](https://www.kdnuggets.com/wp-content/uploads/scalar-vector-matrix-tensor.jpg)
Imagem de: https://www.kdnuggets.com/2018/05/wtf-tensor.html

## Visualização canina

Já os matemáticos que gostam de cachorros, preferem pensar em tensores da seguinte forma:

![](https://pbs.twimg.com/media/CvUaME-VIAACHLb.jpg)
Imagem de: https://pbs.twimg.com/media/CvUaME-VIAACHLb.jpg

## Visão Pythonica: Numpy!

Numpy é uma biblioteca em Python para manipulação eficiente de tensores.

In [1]:
import numpy as np  # todo mundo que é legal chama numpy de np ;)

In [17]:
scalar_py = 3
scalar_np = np.array(3)
print(scalar_py, scalar_np)

3 3


In [18]:
vector_py = [1, 2, 3]
vector_np = np.array([1, 2, 3])
print(vector_py, vector_np)

[1, 2, 3] [1 2 3]


In [19]:
matrix_py = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_np = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix_py)
print(matrix_np)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
tensor_py = [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]
tensor_np = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(tensor_py)
print(tensor_np)

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Manipulando tensores

In [37]:
# Esse código python quebra
1 + matrix_py

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [38]:
matrix_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# Esse código numpy roda lindo
# Somar um valor a todos os elementos de uma matriz nunca foi tao fácil!
1 + matrix_np

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [40]:
# Transposta de uma matriz
matrix_np.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
# Multiplicação de matrizes
matrix_np.dot(matriz_np)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [42]:
# Somar uma lista a todas as linhas de uma matriz nunca foi tao fácil!
[1, 2, 3] + matrix_np

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

Depois de ler isso tudo sobre tensores, você deve estar pensando: "Beleza, mas... para que redes neurais usam esses tais tensores?". Resposta: **para representar as entradas**.

- nas **Redes Neurais Artificiais (*Artificial Neural Networks*, ANN)**, as entradas vão ser representadas por tensores bi-dimensionais (matrizes). Em geral, **cada linha dessa matriz vai representar uma amostra** do seu banco, enquanto **cada coluna representa um atributo** (também chamada de *feature*). Por exemplo, no seguinte banco de dados:

<img align='center' src='https://cdn-images-1.medium.com/max/1600/1*Qt_pYlwBeHtTewnEdksYKQ.png' width=400>

nós temos **5 amostras** (5 linhas) e **4 atributos** (```sepal length```, ```sepal width```, ```petal length``` e ```petal width```) - a coluna ```target``` nesse banco representa a classe de cada amostra.

- Considerando imagens as entradas vão ser agora representadas por tensores 4-dimensionais. Em geral, a maioria dos frameworks assumem que esses tensores estão no formato ```NxHxWxC```, onde:
    - ```N```: representa a quantidade de imagens no seu banco
    - ```H```: a altura de cada imagem
    - ```W```: a largura de cada imagem
    - ```C```: a quantidade de canais de cada imagem. Imagens em níveis de cinza têm apenas 1 canal, enquanto imagens coloridas possuem 3 canais - vermelho (R), verde (G) e azul (B).

Alguns frameworks também aceitam tensores no formato ```NxCxHxW```, ou seja, os canais da imagem vêm logo após a quantidade de imagens.