In [1]:
import numpy as np

## Introdução à Tensores

Falando em Deep Learning, essas entradas são normalmente **tensores**, isto é, vetores de diferentes dimensões. De maneira matemática, você pode pensar em tensores da seguinte forma:

![](https://www.kdnuggets.com/wp-content/uploads/scalar-vector-matrix-tensor.jpg)
Imagem de: https://www.kdnuggets.com/2018/05/wtf-tensor.html

Já os matemáticos que gostam de cachorros, preferem pensar em tensores da seguinte forma:

![](https://pbs.twimg.com/media/CvUaME-VIAACHLb.jpg)
Imagem de: https://pbs.twimg.com/media/CvUaME-VIAACHLb.jpg

Na prática, um **scalar** é apenas um valor (0-dimensional); um **vetor** é um array de scalares (uni-dimensional); uma **matriz** é um array de vetores (bi-dimensional); e um **tensor** é qualquer vetor com N-dimensões (por exemplo, um cubo é um tensor de 3 dimensões). Vale salientar que, tecnicamente, o conceito de tensor engloba todos eles. Porém, na prática, chamamos de tensores os vetores com 3 ou mais dimensões. Veja [**esse vídeo**](https://www.youtube.com/watch?v=f5liqUk0ZTw) para mais detalhes.

Em termos de código, tais estruturas são representadas da seguinte forma:

In [2]:
scalar = 3
print(scalar)

3


In [3]:
vetor = np.array([1, 2, 3])
print(vetor)

[1 2 3]


In [4]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(tensor)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Ainda pensando dessa forma, poderíamos imaginar um tensor 4-dimensional como um **array de cubos**; um tensor 5-dimensional seria uma **matriz de cubos**; um tensor 6-dimensional seria um **cubo de cubos**, e assim por diante...

<img align='center' src='https://media3.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif'>

Depois de ler isso tudo sobre tensores, você deve estar pensando: "Beleza, mas... para que redes neurais usam esses tais tensores?". Resposta: **para representar as entradas**.

- nas **Redes Neurais Artificiais (*Artificial Neural Networks*, ANN)**, as entradas vão ser representadas por tensores bi-dimensionais (matrizes). Em geral, **cada linha dessa matriz vai representar uma amostra** do seu banco, enquanto **cada coluna representa um atributo** (também chamada de *feature*). Por exemplo, no seguinte banco de dados:

<img align='center' src='https://cdn-images-1.medium.com/max/1600/1*Qt_pYlwBeHtTewnEdksYKQ.png' width=400>

nós temos **5 amostras** (5 linhas) e **4 atributos** (```sepal length```, ```sepal width```, ```petal length``` e ```petal width```) - a coluna ```target``` nesse banco representa a classe de cada amostra.

- nas **Redes Neurais Convolucionais** (*Convolutional Neural Networks, CNN*), as entradas vão ser agora representadas por tensores 4-dimensionais. Em geral, a maioria dos frameworks assumem que esses tensores estão no formato ```NxHxWxC```, onde:
    - ```N```: representa a quantidade de imagens no seu banco
    - ```H```: a altura de cada imagem
    - ```W```: a largura de cada imagem
    - ```C```: a quantidade de canais de cada imagem. Imagens em níveis de cinza têm apenas 1 canal, enquanto imagens coloridas possuem 3 canais - vermelho (R), verde (G) e azul (B).

Alguns frameworks também aceitam tensores no formato ```NxCxHxW```, ou seja, os canais da imagem vêm logo após a quantidade de imagens.