# Introdução ao Numpy

De acordo com as próprias palavras da [numpy.org](https://www.numpy.org) (tradução livre): 

> **Numpy** é um pacote fundamental pra computação científica com Python.

E de fato, numpy é muito show! É bem fácil de usar e se usado corretamente super eficiente: 10/10.

Entre outras coisas, o numpy possui:

- um podereso ferramental para manipulação de arrays multi-dimensionais
- funções de broadcasting sofisticadas (veremos isso já já)
- ferramentas para integração de código Fortran e C/C++ (por baixo dos panos pra gente não ter que se preocupar)
- utilidades para álgebra linear, tranformação de Fourier e números aleatórios

Para usar o numpy, tudo que precisamos é importá-lo:

In [1]:
# Programador é bixo preguiçoso então chamamamos numpy de np
# pq numpy é muito grande pra ficar digitando toda hora
import numpy as np

**Ta... o que nós podemos fazer com numpy?**

Bem eu disse que numpy possui "um podereso ferramental para manipulação de arrais multi-dimensionais".

**o que danado isso significa?**

MÁGICA!

Vamos começar criando um array numpy. Um array numpy parece igualzinho a uma lista em python, mas não se engane, não é!

In [2]:
# Lista em python: xoxo e sem grassa
list_py = [1, 2, 3]

# Array numpy: cool e descolado
vector_np = np.array([1, 2, 3])

print('list python:', type(list_py), list_py)
print('vetor numpy', type(vector_np), vector_np)

list python: <class 'list'> [1, 2, 3]
vetor numpy <class 'numpy.ndarray'> [1 2 3]


Humm... okay, vamos tentar dar um append nas listas...

In [3]:
# Ok!
vector_py.append(1)

# Erro!
vector_np.append(1)

NameError: name 'vector_py' is not defined

Não existe append diretamente em um vetor numpy... Mas você pode fazer append via numpy...

In [ ]:
vector_np = np.append(vector_np, 1)

Mas fica aquele velho ditado: não é porque você pode que você deve!

Normalmente não executamos `append` em vetores numpy, eles já nascem prontinhos e realizamos operações entre vetores (adição, multiplicação, transposição, ...). Não adicionamos ou removemos valores de vetores numpy. 

Por que? Em geral isso é ineficiente, olha o exemplo abaixo.

> Obs: Para mais detalhes da uma olhada nesses links [1](https://www.quora.com/Is-it-better-to-use-np-append-or-list-append), [2](https://stackoverflow.com/questions/7869095/concatenate-numpy-arrays-without-copying).


In [ ]:
import time

N = 100000

# Usando uma lista python e depois convertendo para numpy
def time_to_create_vector_py():
    start = time.time()
    
    l = []
    for i in range(N):
        l.append(i)
        
    l = np.array(l)
    return time.time() - start

# Usando um vetor numpy desde o inicio pq sou teimoso
def time_to_create_vector_np():
    start = time.time()
    
    l = np.array([])
    for i in range(N):
        l = np.append(l, i)
        
    l = np.array(l, dtype=int)
    return time.time() - start
    
    
print('Tempo utilizando lista: %.3f (s)' % time_to_create_vector_py())
print('Tempo utilizando numpy: %.3f (s)' % time_to_create_vector_np())

Ta, então uma vez que a gente cria um array numpy, normalmente não alteramos ele via operações convencionais de modificação de lista.

Se você para pra pensar isso faz todo sentido: já que um array numpy não é uma lista python, mas sim um **vetor**.

Já que temos vetores, temos propriedades de vetores associadas aos arrays numpy:
   * Vamos chamar o número de dimensões de um vetor de **ndim**;
   * O **shape** é uma tupla de inteiros do tamanho do **ndim** que fornece número de elementos ao longo de cada dimensão.

In [ ]:
vector_np

Quanto é o ndim desse vetor?

In [ ]:
# 1 pq só temos uma dimensão
vector_np.ndim

E o formato?

In [ ]:
vector_np.shape

E se em vez de um array tivermos um número?

In [ ]:
scalar_np = np.array(3)

# 0 pq não temos nenhuma dimensão
print(scalar_np.ndim)

print(scalar_np.shape)

E matrizes?

In [ ]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_np = np.array(matrix)

print(matrix_np.ndim)

# (3, 3) pq é uma matrix 3x3
print(matrix_np.shape)

O céu é o limite!

In [ ]:
a = np.array([1, 2, 3]) # cria uma matriz de 1 dimensão (vetor)
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64) # cria uma matriz de 2 dimensões (matriz)
print('Vetor a:', a, '\nFormato de a:', a.shape)
print('----------------')
print('Vetor b:\n', b, '\nFormato de b:', b.shape)

In [ ]:
tensor_np = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

tensor_np.shape

## Mágica com Numpy

### Broadcast

Esse código python quebra por que não da pra somar inteiro com lista.

In [ ]:
1 + matrix

Mas pensa um pouco... o código faz "sentido", parece que 1 deveria ser somado a cada elemento da lista.

Bem que dava pra python ser mais esperto e entender que o que a gente quer é na verdade **propagar** o 1 por toda a matriz somando cada elemento a 1.

Essa propagação é justamente o que chamamos de [**broadcasting**](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html). Que é a ideia de que vetores de tamanhos e formatos diferentes são compatíveis para certas operações em alguns casos!

In [ ]:
matrix_np

In [ ]:
# Esse código numpy roda lindo
# Somar um valor a todos os elementos de uma matriz nunca foi tao fácil!
1 + matrix_np

Por que?

Porque numpy consegue entender a partir dos formatos dos vetores o que deve ser feito. O que acontece se tentarmos somar um vetor de tamanho 3 a matriz?

In [ ]:
# Somar uma lista a todas as linhas de uma matriz nunca foi tao fácil!
[1, 2, 3] + matrix_np

Sem broadcasting, como faríamos a operação acima?

In [ ]:
v = np.array([1, 2, 3])
v

In [ ]:
vv = np.tile(v, (3, 1)) # Cria 4 cópias de v e empilha
vv

In [ ]:
matrix_np + vv

O broadcasting nos permite obter o mesmo resultado sem precisar criar cópias do vetor. Sendo mais eficiente tanto em tempo quanto em memória. Além de simplificar bastante a nossa vida.

In [ ]:
# Somar uma lista a todas as colunas de uma matriz nunca foi tao fácil!
np.array([[1], [2], [3]]) + matrix_np

Vai ter caso que vai dar errado?

In [ ]:
# Somar uma lista a todas as linhas de uma matriz nunca foi tao... eita perainda quebrou aqui
[1, 2] + matrix_np

O que aconteceu foi que os formatos dos vetores não são compatíveis, então numpy não conseguiu realizar broadcast corretamente para realizar a operação.

O que é até intuitivo, o que danado a gente estava esperando somando um vetor de tamanho 2 com uma matriz 3x3?

Existe um algoritmo que podemos utilizar pra saber se o broadcast vai dar certo:

* Recebemos a e b
* Percorremos os formatos de a e b de trás pra frente
* Para cada uma das dimensões dim_a e dim_b deve ser verdade que:
   * dim_a == dim_b ou dim_a == 1 ou dim_b == 1

Pense um pouco a respeito... e tende adivinhar os formatos de cada vetor e se os pares são passíveis de broadcast:

* Caso 1: [1, 2] e [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
* Caso 2: [1] e [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
* Caso 3: [[[[[1]]]]] e [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
* Caso 4: [1, 2] e [[1, 2], [4, 5], [7, 8]]

O código da checagem e soluções seguem logo abaixo.

In [ ]:
def is_broadcast_possible(a, b):
    # Oferecimento: https://stackoverflow.com/questions/47243451/checking-if-two-arrays-are-broadcastable-in-python
    a, b = np.array(a), np.array(b)
    print('Formato de a:', a.shape)
    print('Formato de b:', b.shape)
    return all((m == n) or (m == 1) or (n == 1) for m, n in zip(a.shape[::-1], b.shape[::-1]))

In [ ]:
is_broadcast_possible([1, 2], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
is_broadcast_possible([1], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
is_broadcast_possible([[[[[1]]]]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
is_broadcast_possible([1, 2], [[1, 2], [4, 5], [7, 8]])

### Manipulação de matrizes

In [ ]:
# Transposta de uma matriz
matrix_np.transpose()

In [ ]:
# Multiplicação de matrizes
matrix_np.dot(matrix_np)

### Criando tipos específicos de arrays

In [ ]:
np.zeros((3, 3))

In [ ]:
np.ones((3, 3))

In [ ]:
np.full((3, 3), 7)

In [ ]:
np.eye(3)

In [4]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [5]:
np.diag([1, 2, 3], k=1) # k = offset da diagonal

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [6]:
np.mgrid[1:4, 1:4] # similar ao meshgrid no Matlab

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [7]:
np.random.rand(3, 3) # distribuição aleatória

array([[ 0.72271579,  0.75699691,  0.76913937],
       [ 0.44569462,  0.41633378,  0.53022907],
       [ 0.76269823,  0.04796761,  0.55189668]])

In [8]:
np.random.randn(3, 3) # distribuição normal (gaussiana)

array([[ 1.06596232,  0.40504138, -0.67914366],
       [ 2.15538134, -1.14279207, -0.19605287],
       [ 1.56699966, -0.13326904, -0.40451623]])

In [9]:
np.random.randint(1, 10, (3, 3)) # número aleatórios inteiros de 1 a 10

array([[6, 3, 7],
       [2, 9, 6],
       [1, 2, 9]])

**np.arange([start,] stop[,step,], dtype=None)**

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1, 10, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [13]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [14]:
np.arange(1, 10, 2, dtype=np.float64)

array([ 1.,  3.,  5.,  7.,  9.])

**np.linspace(start, stop, num=50, endpoint=True, retstep=False)**

In [15]:
np.linspace(1, 5, num=10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [16]:
np.linspace(0, 2, num=4)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ])

In [17]:
np.linspace(0, 2, num=4, endpoint=False)

array([ 0. ,  0.5,  1. ,  1.5])

## Examinando um array n-dimensional

In [18]:
ds = np.array([[1,2,3],[4,5,6],[7,8,9]])
ds.ndim

2

In [19]:
ds.shape

(3, 3)

In [20]:
ds.size

9

In [21]:
ds.dtype  # tipo dos elementos guardados

dtype('int64')

In [22]:
ds.itemsize  # qtde de bytes por valor

8

In [23]:
ds.size * ds.itemsize  # espaço total ocupado em memória (em bytes)

72

## Análise Estatística

In [24]:
data_set = np.random.random((2, 3))
data_set

array([[ 0.3910871 ,  0.51384096,  0.06134955],
       [ 0.44912327,  0.75356124,  0.189475  ]])

**np.max(a, axis=None, out=None, keepdims=False)**

In [25]:
np.max(data_set)

0.75356124466147945

In [26]:
np.max(data_set, axis=0)

array([ 0.44912327,  0.75356124,  0.189475  ])

In [27]:
np.max(data_set, axis=1)

array([ 0.51384096,  0.75356124])

**np.min(a, axis=None, out=None, keepDims=False)**

In [28]:
np.min(data_set)

0.061349549594220454

**np.mean(a, axis=None, dtype=None, out=None, keepdims=False)**

In [29]:
np.mean(data_set)

0.39307285420132937

**np.median(a, axis=None, out=None, overwrite_input=False)**

In [30]:
np.median(data_set)

0.42010518440828309

**np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)**

In [31]:
np.std(data_set)

0.22329906824172821

**np.sum(a, axis=None, dtype=None, out=None, keepdims=False)**

In [32]:
np.sum(data_set)

2.3584371252079763

**np.prod(a, axis=None, dtype=None, out=None, keepdims=False)**

In [33]:
np.prod(data_set)

0.00079058691504918055

**np.cumsum(a, axis=None, dtype=None, out=None)**

In [34]:
np.cumsum(data_set)

array([ 0.3910871 ,  0.90492806,  0.96627761,  1.41540088,  2.16896212,
        2.35843713])

**np.cumprod(a, axis=None, dtype=None, out=None)**

In [35]:
np.cumprod(data_set)

array([ 0.3910871 ,  0.20095657,  0.0123286 ,  0.00553706,  0.00417251,
        0.00079059])

## Redimensionando Arrays

#### **np.reshape(a, newshape, order='C')**

In [36]:
np.reshape(data_set, (3, 2))

array([[ 0.3910871 ,  0.51384096],
       [ 0.06134955,  0.44912327],
       [ 0.75356124,  0.189475  ]])

In [37]:
np.reshape(data_set, (6, 1))

array([[ 0.3910871 ],
       [ 0.51384096],
       [ 0.06134955],
       [ 0.44912327],
       [ 0.75356124],
       [ 0.189475  ]])

In [38]:
np.reshape(data_set, 6)

array([ 0.3910871 ,  0.51384096,  0.06134955,  0.44912327,  0.75356124,
        0.189475  ])

**np.ravel(a, order='C')**

In [39]:
np.ravel(data_set)

array([ 0.3910871 ,  0.51384096,  0.06134955,  0.44912327,  0.75356124,
        0.189475  ])

In [40]:
data_set.flatten() # igual ao ravel

array([ 0.3910871 ,  0.51384096,  0.06134955,  0.44912327,  0.75356124,
        0.189475  ])

## Acessando elementos

### Indexação

In [41]:
data_set = np.random.randint(1, 10, (5, 5))
data_set

array([[8, 2, 4, 7, 7],
       [9, 1, 5, 4, 7],
       [8, 4, 8, 9, 4],
       [4, 2, 1, 3, 3],
       [6, 7, 9, 7, 5]])

In [42]:
data_set[1] # segunda linha

array([9, 1, 5, 4, 7])

In [43]:
data_set[1][0] # segunda linha, primeira coluna 

9

In [44]:
data_set[1, 0] # equivalente a de cima

9

#### Indexação por inteiros

Quando você indexa matrizes numpy usando *slicing*, a matriz resultante sempre será um subarray da matriz original. Por outro lado, a indexação de matrizes por inteiros permite que você construa matrizes arbitrárias usando os dados de outra matriz. Aqui está um exemplo:

In [45]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [47]:
np.array([a[0, 0], a[1, 1], a[2, 0]]) # equivalente ao de cima

array([1, 4, 5])

#### Indexação booleana

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [48]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [50]:
print(a[bool_idx])

[3 4 5 6]


In [51]:
print(a[a > 2])

[3 4 5 6]


### Slicing

In [52]:
data_set[2:4] # terceira e quarta linhas

array([[8, 4, 8, 9, 4],
       [4, 2, 1, 3, 3]])

In [53]:
data_set[2:4, 0] # terceira e quarta linhas, primeira coluna

array([8, 4])

In [54]:
data_set[2:4, 0:2] # terceira e quarta linhas, primeira e segunda coluna

array([[8, 4],
       [4, 2]])

In [55]:
data_set[:, 0] # todas as linhas, primeira coluna

array([8, 9, 8, 4, 6])

### Steping

In [56]:
data_set[:, 0:10:2] # 1ª, 3ª, 5ª, 7ª e 9ª colunas para todas as linhas

array([[8, 4, 7],
       [9, 5, 7],
       [8, 8, 4],
       [4, 1, 3],
       [6, 9, 5]])

In [57]:
data_set[::]

array([[8, 2, 4, 7, 7],
       [9, 1, 5, 4, 7],
       [8, 4, 8, 9, 4],
       [4, 2, 1, 3, 3],
       [6, 7, 9, 7, 5]])

In [58]:
data_set[::2] # 1ª, 3ª e 5ª linha, todas as colunas

array([[8, 2, 4, 7, 7],
       [8, 4, 8, 9, 4],
       [6, 7, 9, 7, 5]])

## Operações com matrizes

In [59]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [60]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [61]:
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [62]:
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [63]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Observe que, diferentemente do MATLAB, $*$ é a multiplicação elementar, não a multiplicação de matrizes. Em vez disso, usamos a função **dot** para calcular produtos internos de vetores, multiplicar um vetor por uma matriz e multiplicar matrizes. 

In [64]:
v = np.array([9, 10])
w = np.array([11, 12])

# produto interno
print(v.dot(w))
print(np.dot(v, w))

219
219


In [65]:
# multiplicação entre matriz (x) e vetor (v)
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [66]:
# multiplicação de matriz
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [67]:
# transposta
print(x.T)

print('-------------')
# ou
print(np.transpose(x))

[[1 3]
 [2 4]]
-------------
[[1 3]
 [2 4]]


Lista de todas as operações: <a href="http://docs.scipy.org/doc/numpy/reference/routines.math.html"> documentation</a>.